// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: pkg/proto/profile/profile.proto

package profile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileGrpcService_CreateProfile_FullMethodName = "/ProfileGrpcService/CreateProfile"
)

// ProfileGrpcServiceClient is the client API for ProfileGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfileGrpcServiceClient interface {
	CreateProfile(ctx context.Context, in *ProfileRequestDto, opts ...grpc.CallOption) (*ProfileResponseDto, error)
}

type profileGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileGrpcServiceClient(cc grpc.ClientConnInterface) ProfileGrpcServiceClient {
	return &profileGrpcServiceClient{cc}
}

func (c *profileGrpcServiceClient) CreateProfile(ctx context.Context, in *ProfileRequestDto, opts ...grpc.CallOption) (*ProfileResponseDto, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponseDto)
	err := c.cc.Invoke(ctx, ProfileGrpcService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileGrpcServiceServer is the server API for ProfileGrpcService service.
// All implementations must embed UnimplementedProfileGrpcServiceServer
// for forward compatibility.
type ProfileGrpcServiceServer interface {
	CreateProfile(context.Context, *ProfileRequestDto) (*ProfileResponseDto, error)
	mustEmbedUnimplementedProfileGrpcServiceServer()
}

// UnimplementedProfileGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileGrpcServiceServer struct{}

func (UnimplementedProfileGrpcServiceServer) CreateProfile(context.Context, *ProfileRequestDto) (*ProfileResponseDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedProfileGrpcServiceServer) mustEmbedUnimplementedProfileGrpcServiceServer() {}
func (UnimplementedProfileGrpcServiceServer) testEmbeddedByValue()                            {}

// UnsafeProfileGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileGrpcServiceServer will
// result in compilation errors.
type UnsafeProfileGrpcServiceServer interface {
	mustEmbedUnimplementedProfileGrpcServiceServer()
}

func RegisterProfileGrpcServiceServer(s grpc.ServiceRegistrar, srv ProfileGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfileGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileGrpcService_ServiceDesc, srv)
}

func _ProfileGrpcService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequestDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileGrpcServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileGrpcService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileGrpcServiceServer).CreateProfile(ctx, req.(*ProfileRequestDto))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileGrpcService_ServiceDesc is the grpc.ServiceDesc for ProfileGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProfileGrpcService",
	HandlerType: (*ProfileGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProfile",
			Handler:    _ProfileGrpcService_CreateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/profile/profile.proto",
}
